export const DUMMY_CAREGIVERS = [
    {
        "id": "cg-auto-1",
        "name": "Caregiver 1",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Frosinone",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-2",
        "name": "Caregiver 2",
        "role": "caregiver",
        "region": "Campania",
        "province": "Caserta",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-3",
        "name": "Caregiver 3",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-4",
        "name": "Caregiver 4",
        "role": "caregiver",
        "region": "Campania",
        "province": "Napoli",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-5",
        "name": "Caregiver 5",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Milano",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-6",
        "name": "Caregiver 6",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Frosinone",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-7",
        "name": "Caregiver 7",
        "role": "caregiver",
        "region": "Campania",
        "province": "Caserta",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-8",
        "name": "Caregiver 8",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Frosinone",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-9",
        "name": "Caregiver 9",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-10",
        "name": "Caregiver 10",
        "role": "caregiver",
        "region": "Piemonte",
        "province": "Torino",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-11",
        "name": "Caregiver 11",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-12",
        "name": "Caregiver 12",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Frosinone",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-13",
        "name": "Caregiver 13",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Frosinone",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-14",
        "name": "Caregiver 14",
        "role": "caregiver",
        "region": "Piemonte",
        "province": "Novara",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-15",
        "name": "Caregiver 15",
        "role": "caregiver",
        "region": "Piemonte",
        "province": "Cuneo",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-16",
        "name": "Caregiver 16",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Latina",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-17",
        "name": "Caregiver 17",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Bergamo",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-18",
        "name": "Caregiver 18",
        "role": "caregiver",
        "region": "Piemonte",
        "province": "Torino",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-19",
        "name": "Caregiver 19",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Latina",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-20",
        "name": "Caregiver 20",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Milano",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-21",
        "name": "Caregiver 21",
        "role": "caregiver",
        "region": "Piemonte",
        "province": "Cuneo",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-22",
        "name": "Caregiver 22",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-23",
        "name": "Caregiver 23",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Bergamo",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-24",
        "name": "Caregiver 24",
        "role": "caregiver",
        "region": "Campania",
        "province": "Napoli",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-25",
        "name": "Caregiver 25",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Frosinone",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-26",
        "name": "Caregiver 26",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Milano",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-27",
        "name": "Caregiver 27",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Bergamo",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-28",
        "name": "Caregiver 28",
        "role": "caregiver",
        "region": "Campania",
        "province": "Caserta",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-29",
        "name": "Caregiver 29",
        "role": "caregiver",
        "region": "Piemonte",
        "province": "Torino",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-30",
        "name": "Caregiver 30",
        "role": "caregiver",
        "region": "Campania",
        "province": "Salerno",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-31",
        "name": "Caregiver 31",
        "role": "caregiver",
        "region": "Campania",
        "province": "Salerno",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-32",
        "name": "Caregiver 32",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Roma",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-33",
        "name": "Caregiver 33",
        "role": "caregiver",
        "region": "Campania",
        "province": "Caserta",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-34",
        "name": "Caregiver 34",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-35",
        "name": "Caregiver 35",
        "role": "caregiver",
        "region": "Piemonte",
        "province": "Cuneo",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-36",
        "name": "Caregiver 36",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Milano",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-37",
        "name": "Caregiver 37",
        "role": "caregiver",
        "region": "Piemonte",
        "province": "Novara",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-38",
        "name": "Caregiver 38",
        "role": "caregiver",
        "region": "Piemonte",
        "province": "Novara",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-39",
        "name": "Caregiver 39",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Frosinone",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-40",
        "name": "Caregiver 40",
        "role": "caregiver",
        "region": "Campania",
        "province": "Caserta",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-41",
        "name": "Caregiver 41",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Roma",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-42",
        "name": "Caregiver 42",
        "role": "caregiver",
        "region": "Campania",
        "province": "Napoli",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-43",
        "name": "Caregiver 43",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Latina",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-44",
        "name": "Caregiver 44",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-45",
        "name": "Caregiver 45",
        "role": "caregiver",
        "region": "Lazio",
        "province": "Latina",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-46",
        "name": "Caregiver 46",
        "role": "caregiver",
        "region": "Campania",
        "province": "Caserta",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-47",
        "name": "Caregiver 47",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-48",
        "name": "Caregiver 48",
        "role": "caregiver",
        "region": "Campania",
        "province": "Salerno",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-49",
        "name": "Caregiver 49",
        "role": "caregiver",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    },
    {
        "id": "cg-auto-50",
        "name": "Caregiver 50",
        "role": "caregiver",
        "region": "Piemonte",
        "province": "Cuneo",
        "raw_competenze_esperienze": "Esperienza pluriennale nell'assistenza domiciliare, igiene personale, cucina e supporto quotidiano.",
        "raw_approccio_cura": "Approccio empatico e professionale, orientato all'ascolto e al rispetto della persona.",
        "raw_stile_relazionale": "Lettura, passeggiate, cucina, musica o attività rilassanti.",
        "raw_gestione_stress": "Preferenza per ritmi regolari, disponibile a turni lunghi o flessibili, nessuna allergia rilevante.",
        "raw_valori_personali": "Rispetto reciproco, comunicazione chiara, fiducia e collaborazione."
    }
];

export const DUMMY_DISABLED_PEOPLE = [
    {
        "id": "dp-auto-1",
        "name": "Persona 1",
        "role": "disabled",
        "region": "Campania",
        "province": "Salerno",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-2",
        "name": "Persona 2",
        "role": "disabled",
        "region": "Lazio",
        "province": "Frosinone",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-3",
        "name": "Persona 3",
        "role": "disabled",
        "region": "Lazio",
        "province": "Frosinone",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-4",
        "name": "Persona 4",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Torino",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-5",
        "name": "Persona 5",
        "role": "disabled",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-6",
        "name": "Persona 6",
        "role": "disabled",
        "region": "Lombardia",
        "province": "Bergamo",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-7",
        "name": "Persona 7",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Torino",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-8",
        "name": "Persona 8",
        "role": "disabled",
        "region": "Lombardia",
        "province": "Milano",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-9",
        "name": "Persona 9",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Torino",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-10",
        "name": "Persona 10",
        "role": "disabled",
        "region": "Campania",
        "province": "Salerno",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-11",
        "name": "Persona 11",
        "role": "disabled",
        "region": "Campania",
        "province": "Salerno",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-12",
        "name": "Persona 12",
        "role": "disabled",
        "region": "Lazio",
        "province": "Latina",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-13",
        "name": "Persona 13",
        "role": "disabled",
        "region": "Campania",
        "province": "Caserta",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-14",
        "name": "Persona 14",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Novara",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-15",
        "name": "Persona 15",
        "role": "disabled",
        "region": "Campania",
        "province": "Napoli",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-16",
        "name": "Persona 16",
        "role": "disabled",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-17",
        "name": "Persona 17",
        "role": "disabled",
        "region": "Campania",
        "province": "Caserta",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-18",
        "name": "Persona 18",
        "role": "disabled",
        "region": "Lazio",
        "province": "Roma",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-19",
        "name": "Persona 19",
        "role": "disabled",
        "region": "Lazio",
        "province": "Latina",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-20",
        "name": "Persona 20",
        "role": "disabled",
        "region": "Campania",
        "province": "Caserta",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-21",
        "name": "Persona 21",
        "role": "disabled",
        "region": "Campania",
        "province": "Salerno",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-22",
        "name": "Persona 22",
        "role": "disabled",
        "region": "Campania",
        "province": "Salerno",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-23",
        "name": "Persona 23",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Cuneo",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-24",
        "name": "Persona 24",
        "role": "disabled",
        "region": "Campania",
        "province": "Caserta",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-25",
        "name": "Persona 25",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Novara",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-26",
        "name": "Persona 26",
        "role": "disabled",
        "region": "Lazio",
        "province": "Latina",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-27",
        "name": "Persona 27",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Novara",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-28",
        "name": "Persona 28",
        "role": "disabled",
        "region": "Lazio",
        "province": "Latina",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-29",
        "name": "Persona 29",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Cuneo",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-30",
        "name": "Persona 30",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Cuneo",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-31",
        "name": "Persona 31",
        "role": "disabled",
        "region": "Lombardia",
        "province": "Bergamo",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-32",
        "name": "Persona 32",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Torino",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-33",
        "name": "Persona 33",
        "role": "disabled",
        "region": "Lombardia",
        "province": "Brescia",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-34",
        "name": "Persona 34",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Torino",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-35",
        "name": "Persona 35",
        "role": "disabled",
        "region": "Lazio",
        "province": "Roma",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-36",
        "name": "Persona 36",
        "role": "disabled",
        "region": "Campania",
        "province": "Napoli",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-37",
        "name": "Persona 37",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Torino",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-38",
        "name": "Persona 38",
        "role": "disabled",
        "region": "Campania",
        "province": "Salerno",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-39",
        "name": "Persona 39",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Cuneo",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-40",
        "name": "Persona 40",
        "role": "disabled",
        "region": "Lazio",
        "province": "Frosinone",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-41",
        "name": "Persona 41",
        "role": "disabled",
        "region": "Lazio",
        "province": "Latina",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-42",
        "name": "Persona 42",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Novara",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-43",
        "name": "Persona 43",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Torino",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-44",
        "name": "Persona 44",
        "role": "disabled",
        "region": "Lazio",
        "province": "Roma",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-45",
        "name": "Persona 45",
        "role": "disabled",
        "region": "Campania",
        "province": "Napoli",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-46",
        "name": "Persona 46",
        "role": "disabled",
        "region": "Lazio",
        "province": "Roma",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-47",
        "name": "Persona 47",
        "role": "disabled",
        "region": "Piemonte",
        "province": "Novara",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-48",
        "name": "Persona 48",
        "role": "disabled",
        "region": "Lombardia",
        "province": "Milano",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-49",
        "name": "Persona 49",
        "role": "disabled",
        "region": "Lazio",
        "province": "Latina",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    },
    {
        "id": "dp-auto-50",
        "name": "Persona 50",
        "role": "disabled",
        "region": "Lazio",
        "province": "Roma",
        "raw_contexto_vita": "Vive in un appartamento adattato, con familiari o solo, ambiente tranquillo.",
        "raw_bisogni_assistenziali": "Necessita supporto per alcune attività quotidiane come igiene, cucina o spostamenti.",
        "raw_stile_relazionale": "Ha interessi personali come musica, lettura, conversazione o hobby creativi.",
        "raw_ritmo_quotidiano": "Preferisce una giornata con ritmi definiti ma flessibili.",
        "raw_valori_convivenza": "Rispetto reciproco, puntualità, dialogo e attenzione alla privacy."
    }
];
